/* Failure Analysis — "Where does it fail?" */
(function () {
  "use strict";
  const { el, pct, skeletonLines, errorBox, card, badge, intentBadge, emptyBox } = UI;

  async function render(root) {
    root.appendChild(skeletonLines(5, "block"));
    let data;
    try {
      data = await API.failures();
    } catch (err) {
      root.replaceChildren(errorBox(err));
      return;
    }

    const modes = data.top_failure_modes || [];
    root.replaceChildren(
      el("div", { class: "page-head" },
        el("h1", { text: "Failure Analysis" }),
        el("p", { class: "desc" },
          "Real misclassifications of the human-verified golden set — generated by scripts/analyze_failures.py, ",
          "not invented. Every example below is an actual failure with its predicted vs. actual intent.")),
      el("div", { class: "grid cols-3 mb-4" },
        statBox("Failures analyzed", String(data.n_failures ?? "—"), `of ${data.golden_set_size ?? "—"} golden examples`),
        statBox("Failure rate", pct(data.failure_rate), "golden-set misclassification rate"),
        statBox("Failure categories", String(modes.length), "distinct structural modes")),
      data.brand ? el("p", { class: "hint mb-3", text: `Brand: ${data.brand} · report fields: n_failures=${data.n_failures}, golden_set_size=${data.golden_set_size}` }) : null,
      ...modes.map((m) => modeCard(m))
    );
  }

  function statBox(label, value, sub) {
    return el("div", { class: "stat" },
      el("div", { class: "label", text: label }),
      el("div", { class: "value", text: value }),
      el("div", { class: "sub", text: sub }));
  }

  function modeCard(mode) {
    const bar = el("div", { class: "meter mt-3" },
      el("span", { style: `width: ${((mode.pct_of_failures || 0) * 100).toFixed(1)}%` }));

    const examples = (mode.examples || []).map((ex) =>
      el("div", { class: "evidence-card" },
        el("div", { class: "ev-head" },
          el("span", { class: "mono-badge", text: ex.id }),
          el("div", { class: "row" },
            (ex.categories || "").split(",").filter(Boolean).map((c) => badge(c.trim(), "gray")),
            badge(ex.difficulty || "—", ex.difficulty === "easy" ? "green" : ex.difficulty === "hard" ? "red" : "amber"))),
        el("div", { class: "ev-body" },
          el("div", { class: "quote", style: "border-left-color: var(--accent-border)" }, ex.message),
          el("div", { class: "row wrap small" },
            el("span", { class: "text-muted", text: "predicted:" }), intentBadge(ex.predicted_intent),
            el("span", { class: "text-muted", text: "actual:" }), intentBadge(ex.true_intent),
            el("span", { class: "text-muted", text: "confidence:" }), el("strong", { text: UI.num(ex.confidence) }))),
        el("div", { class: "small mt-3" },
          el("span", { class: "verdict incorrect", text: "✗ Why it failed: " }),
          el("span", { class: "text-secondary", text: hypothesisFor(mode, ex) }))));

    // NOTE: the title MUST be a plain string. UI.card() renders the title with
    // textContent — passing a DOM element here previously produced the literal
    // text "[object HTMLSpanElement]" in the header (the count badge now lives
    // in the card's actions slot instead).
    return card(
      `${mode.category} — ${mode.count} failures`,
      el("div", null,
        el("p", { class: "small text-secondary" },
          el("strong", { text: "Hypothesis: " }), mode.hypothesis || ""),
        bar,
        el("div", { class: "mt-4 section-title", text: "Real examples" }),
        examples.length ? examples : emptyBox("No examples stored for this category")),
      badge(`${pct(mode.pct_of_failures)} of failures`, "red")
    );
  }

  /* Category-level explanation, with per-example nuance where available. */
  function hypothesisFor(mode, ex) {
    const base = (mode.hypothesis || "").split(" Fix:")[0].trim();
    if (mode.category === "ambiguous_intent") {
      return `${base} The classifier chose "${ex.predicted_intent}" with confidence ${UI.num(ex.confidence)}, but "${ex.true_intent}" fits about equally well — a top-2 margin this narrow now feeds the ambiguity signal and escalates.`;
    }
    if (mode.category === "multi_intent_message") {
      return `${base} This message raises several issues at once; under the current policy it is flagged multi-intent and escalated rather than answered for one issue in isolation.`;
    }
    if (mode.category === "out_of_distribution") {
      return `${base} The message does not cleanly fit any of the 12 taxonomy intents; the classifier confidently chose "${ex.predicted_intent}" instead of recognizing novelty.`;
    }
    return base;
  }

  window.Pages = window.Pages || {};
  window.Pages.failures = render;
})();
